name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
       java-version: '17'
       distribution: 'temurin'

    - name: Build and test Spring Boot application
      run: |
        chmod +x mvnw
        ./mvnw clean package -DskipTests=false


    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@v1
      with:
        mongodb-version: 'latest'
        distribution: 'linux'


  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
       java-version: '17'
       distribution: 'temurin'

    - name: Run all tests
      run: |
        chmod +x mvnw
        ./mvnw test     
